<a href="https://colab.research.google.com/github/ID-L0NG3/Analytics-Project/blob/main/Demographic_Data_Analyser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd

In [16]:
from google.colab import files
uploaded = files.upload()

Saving adult.data.csv to adult.data (1).csv

In [17]:
import io
uploaded_filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[uploaded_filename]))
display(df)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
display(df.dtypes)

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

In [ ]:
# Percentage representation of races in dataframe
total_people = df.shape[0]
race_counts = df['race'].value_counts()
race_percentages = (race_counts / total_people) * 100
display(race_percentages)

race
White                 85.427352
Black                  9.594300
Asian-Pac-Islander     3.190934
Amer-Indian-Eskimo     0.955130
Other                  0.832284
Name: count, dtype: float64

In [ ]:
# Average age of men
df_filtered = df[df['sex'] == 'Male'].copy()
average_age_men = df_filtered['age'].mean()
print(f"The average age of men is {average_age_men:.2f} years.")

The average age of men is 39.43 years.

In [ ]:
# Percentage of people with a Bachelor's Degree
df_filtered = df[df['education'] == 'Bachelors'].copy()
total_people = df.shape[0]
bachelors_count = df_filtered.shape[0]
bachelors_percentage = (bachelors_count / total_people) * 100
print(f"{bachelors_percentage:.2f}% of people possess a Bachelor's Degree.")

16.45% of people possess a Bachelor's Degree.

In [ ]:
# Percentage of people with advanced education
df_filtered = df[df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])].copy()
total_people = df.shape[0]
advanced_education_count = df_filtered.shape[0]
advanced_education_percentage = (advanced_education_count / total_people) * 100
print(f"{advanced_education_percentage:.2f}% of people have advanced education.")

23.01% of people have advanced education.

In [ ]:
# Percentage of people with advanced education, that are earning over 50K
df_filtered_1 = df[df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])].copy()
df_filtered_2 = df_filtered_1[df_filtered_1['salary'] == '>50K']
total_people = df_filtered_1.shape[0]
advanced_education_count = df_filtered_2.shape[0]
advanced_education_percentage = (advanced_education_count / total_people) * 100
print(f"{advanced_education_percentage:.2f}% of people with advanced education earn over 50K.")

46.54% of people with advanced education earn over 50K.

In [18]:
# Percentage of people without an advanced education, earning over 50K
df_filtered_1 = df[~df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])].copy()
df_filtered_2 = df_filtered_1[df_filtered_1['salary'] == '>50K']
total_people = df_filtered_1.shape[0]
advanced_education_count = df_filtered_2.shape[0]
advanced_education_percentage = (advanced_education_count / total_people) * 100
print(f"{advanced_education_percentage:.2f}% of people without advanced education earn over 50K.")

17.37% of people without advanced education earn over 50K.

In [22]:
# Minimum amount of hours worked
min_hours = df['hours-per-week'].min()
print(f"The minimum amount of time worked is {min_hours} hour(s).")

The minimum amount of time worked is 1 hour(s).

In [24]:
# Percentage of people working minumum hours AND earning above 50K
df_filtered_1 = df[df['hours-per-week'] == min_hours].copy()
df_filtered_2 = df_filtered_1[df_filtered_1['salary'] == '>50K']
total_people = df_filtered_1.shape[0]
min_hours_count = df_filtered_2.shape[0]
min_hours_percentage = (min_hours_count / total_people) * 100
print(f"{min_hours_percentage}% of people work minimum hours and still earn above 50K")

10.0% of people work minimum hours and still earn above 50K

In [29]:
# Country with the highest number of people earning above 50K
df_filtered = df[df['salary'] == '>50K'].copy()
country_counts = df_filtered['native-country'].value_counts()
total_people = df_filtered.shape[0]
highest_earning_country = country_counts.idxmax()
highest_earning_country_percentage = (country_counts.max() / total_people) *100
print(f"{highest_earning_country} is the country with the highest number of people earning above 50K, with a percentage of {highest_earning_country_percentage:.2f}%")

United-States is the country with the highest number of people earning above 50K, with a percentage of 91.46%

In [30]:
# The most popular job in India, for those earning above 50K
df_filtered = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')].copy()
popular_job = df_filtered['occupation'].value_counts().idxmax()
print(f"The most popular job in India for those earning above 50K is {popular_job}.")

The most popular job in India for those earning above 50K is Prof-specialty.